application: bloggart-demo
version: live
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  script: empty_favicon.py

- url: /apple-touch-icon.png
  script: empty_favicon.py

- url: /apple-touch-icon-precomposed.png
  script: empty_favicon.py

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.application
  login: admin

- url: /admin/.*
  script: admin.application
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: static.application

libraries:
- name: django
  version: "1.2"

# https://code.google.com/p/googleappengine/issues/detail?id=8976
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
